spring:
  datasource:
    url: jdbc:postgresql://localhost/project_development
    username: pivotal
    password:
    driverClassName: org.postgresql.Driver

server:
  address: localhost
  port: 8080